### ISSUE TITLE
User Story: GreptimeDB uses jsonb for it's JSON support

### ISSUE THREAD

**Issue by WenyXu** [databendlabs/jsonb#57]
Hello, everyone!

First off, a big thanks for the excellent JSONB crate. I'm excited to share how [GreptimeDB](https://github.com/greptimeTeam/greptimedb/) (Tracking issue: https://github.com/GreptimeTeam/greptimedb/issues/4230) uses it to add JSON-type support to our database. With JSONB, we've enhanced our capabilities in managing semi-structured data, which is crucial for many of our users who work with flexible schemas.

@CookiePieWw has been leading the integration efforts, and we've already seen great improvements in functionality.

Thanks again for your amazing work!

**Comment by b41sh** [comment]
@WenyXu Thanks, I can give some help if necessary.
