### ISSUE TITLE
Switch from `fast-float` to `fast-float2`?

### ISSUE THREAD

**Issue by penberg** [databendlabs/jsonb#68]
Github's bot claims that `fast-float` has multiple soundness issues:

https://github.com/penberg/limbo/security/dependabot/5

The suggestion is to either move to `fast-float2` or just use the standard library.

**Comment by Xuanwo** [comment]
Thanks for raising this issue and happy to know you are using this crate! This request makes sense, I will take a look over this.

**Comment by Xuanwo** [comment]
Hi, @penberg, please try upgrade jsonb to latest version.

**Comment by penberg** [comment]
Thanks for the quick fix @Xuanwo! 🔥

**Comment by Xuanwo** [comment]
> Thanks for the quick fix @Xuanwo! 🔥

All glory and credit should be given to @b41sh :heart:

Hoping you have fun using `jsonb`.
